# Form implementation generated from reading ui file 'interface/ui/cm_wo_rep.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(512, 310)
        Form.setMinimumSize(QtCore.QSize(512, 310))
        Form.setMaximumSize(QtCore.QSize(512, 310))
        Form.setMouseTracking(False)
        self.formula = QtWidgets.QLabel(parent=Form)
        self.formula.setGeometry(QtCore.QRect(6, 6, 500, 100))
        self.formula.setMinimumSize(QtCore.QSize(500, 100))
        self.formula.setMaximumSize(QtCore.QSize(500, 100))
        self.formula.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.formula.setStyleSheet("border: 1px solid red;\n"
"")
        self.formula.setText("")
        self.formula.setScaledContents(False)
        self.formula.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formula.setObjectName("formula")
        self.back = QtWidgets.QPushButton(parent=Form)
        self.back.setGeometry(QtCore.QRect(6, 270, 88, 34))
        self.back.setObjectName("back")
        self.calculate = QtWidgets.QPushButton(parent=Form)
        self.calculate.setGeometry(QtCore.QRect(420, 270, 88, 34))
        self.calculate.setObjectName("calculate")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 120, 160, 146))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.k = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.k.setObjectName("k")
        self.horizontalLayout_10.addWidget(self.k)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.n = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.n.setObjectName("n")
        self.horizontalLayout_11.addWidget(self.n)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.result = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.result.setEnabled(True)
        self.result.setReadOnly(True)
        self.result.setObjectName("result")
        self.horizontalLayout_12.addWidget(self.result)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.help = QtWidgets.QPushButton(parent=Form)
        self.help.setGeometry(QtCore.QRect(470, 120, 31, 31))
        self.help.setObjectName("help")
        self.clear = QtWidgets.QPushButton(parent=Form)
        self.clear.setGeometry(QtCore.QRect(330, 270, 88, 34))
        self.clear.setObjectName("clear")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Сочетания без повторений"))
        self.back.setText(_translate("Form", "Назад"))
        self.calculate.setText(_translate("Form", "Рассчитать"))
        self.label_11.setText(_translate("Form", "k:"))
        self.label_12.setText(_translate("Form", "n:"))
        self.label_13.setText(_translate("Form", "С:"))
        self.help.setText(_translate("Form", "?"))
        self.clear.setText(_translate("Form", "Очистить"))
