# Form implementation generated from reading ui file 'interface/ui/pr_w_rep.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(512, 310)
        Form.setMinimumSize(QtCore.QSize(512, 310))
        Form.setMaximumSize(QtCore.QSize(512, 310))
        Form.setMouseTracking(False)
        self.formula = QtWidgets.QLabel(parent=Form)
        self.formula.setGeometry(QtCore.QRect(6, 6, 500, 100))
        self.formula.setMinimumSize(QtCore.QSize(500, 100))
        self.formula.setMaximumSize(QtCore.QSize(500, 100))
        self.formula.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.formula.setStyleSheet("border: 1px solid red;\n"
"")
        self.formula.setText("")
        self.formula.setScaledContents(False)
        self.formula.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formula.setObjectName("formula")
        self.back = QtWidgets.QPushButton(parent=Form)
        self.back.setGeometry(QtCore.QRect(6, 270, 88, 34))
        self.back.setObjectName("back")
        self.calculate = QtWidgets.QPushButton(parent=Form)
        self.calculate.setGeometry(QtCore.QRect(420, 270, 88, 34))
        self.calculate.setObjectName("calculate")
        self.help = QtWidgets.QPushButton(parent=Form)
        self.help.setGeometry(QtCore.QRect(470, 120, 31, 31))
        self.help.setObjectName("help")
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 120, 215, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.n_k = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.n_k.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.n_k.setObjectName("n_k")
        self.horizontalLayout.addWidget(self.n_k)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.result = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.result.setEnabled(True)
        self.result.setReadOnly(True)
        self.result.setObjectName("result")
        self.horizontalLayout_2.addWidget(self.result)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.clear = QtWidgets.QPushButton(parent=Form)
        self.clear.setGeometry(QtCore.QRect(330, 270, 88, 34))
        self.clear.setObjectName("clear")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Перестановки с повторениями"))
        self.back.setText(_translate("Form", "Назад"))
        self.calculate.setText(_translate("Form", "Рассчитать"))
        self.help.setText(_translate("Form", "?"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p>n<span style=\" vertical-align:sub;\">1</span>, n<span style=\" vertical-align:sub;\">2, </span>..., n<span style=\" vertical-align:sub;\">k</span>:</p></body></html>"))
        self.label_10.setText(_translate("Form", "P:"))
        self.clear.setText(_translate("Form", "Очистить"))
